function exponents = build_bitcube_support_v08(bitPositions)
%BUILD_BITCUBE_SUPPORT_V08 Exponent support generated by independent bit choices.
%
% exponents = { sum_{b in S} 2^b : S subset of bitPositions }.
% With eight distinct bit positions this produces exactly 256 monomials and
% an 8-node indicator BMD.  v0.8 uses this to keep both operand sizes fixed
% while varying only how one Q bit overlaps P's low-bit band.

bits = double(bitPositions(:).');
if isempty(bits) || any(~isfinite(bits)) || any(bits < 0) || any(bits ~= floor(bits))
    error('BMD:V08Bits','bitPositions must be nonnegative integer bit indices.');
end
if numel(unique(bits)) ~= numel(bits)
    error('BMD:V08Bits','bitPositions must be distinct.');
end
if any(bits > 52)
    error('BMD:V08Bits','bitPositions must be <= 52 for exact double interoperability.');
end

exponents = uint64(0);
for b = bits
    delta = bitshift(uint64(1),b);
    exponents = [exponents exponents + delta]; %#ok<AGROW>
end
exponents = sort(exponents,'ascend');
end
